2019-03-27 12:03:59 - 0 - [main] ERROR com.capgemini.bankapp.client.BankAccountClient  - Withdraw failed
com.cagemini.bankapp.exception.LowBalanceException: You don't have sufficient fund
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.withdraw(BankAccountServiceImpl.java:35)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:60)
2019-03-27 12:14:02 - 1 - [main] ERROR com.capgemini.bankapp.client.BankAccountClient  - Withdraw failed
com.cagemini.bankapp.exception.LowBalanceException: You don't have sufficient fund
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.withdraw(BankAccountServiceImpl.java:35)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:60)
2019-03-27 12:33:30 - 0 - [main] ERROR com.capgemini.bankapp.client.BankAccountClient  - Withdraw failed
com.cagemini.bankapp.exception.LowBalanceException: You don't have sufficient fund
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.withdraw(BankAccountServiceImpl.java:35)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:60)
2019-03-28 10:10:06 - 0 - [main] ERROR com.capgemini.bankapp.client.BankAccountClient  - Account Not Found
com.cagemini.bankapp.exception.BankAccountNotFoundException: BankAccount doesn't exist..
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.checkBalance(BankAccountServiceImpl.java:26)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:90)
2019-03-28 11:03:07 - 15 - [main] ERROR com.capgemini.bankapp.util.DbUtil  - SQL Exception
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:985)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.getMutex(ConnectionImpl.java:3015)
	at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1521)
	at com.capgemini.bankapp.util.DbUtil.commit(DbUtil.java:37)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.withdraw(BankAccountServiceImpl.java:41)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:62)
2019-03-28 11:04:18 - 0 - [main] ERROR com.capgemini.bankapp.util.DbUtil  - SQL Exception
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:985)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.getMutex(ConnectionImpl.java:3015)
	at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1521)
	at com.capgemini.bankapp.util.DbUtil.commit(DbUtil.java:37)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.withdraw(BankAccountServiceImpl.java:41)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:62)
2019-03-28 11:23:40 - 0 - [main] ERROR com.capgemini.bankapp.util.DbUtil  - SQL Exception
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Connection.close() has already been called. Invalid operation in this state.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:985)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.getMutex(ConnectionImpl.java:3015)
	at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1521)
	at com.capgemini.bankapp.util.DbUtil.commit(DbUtil.java:37)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.withdraw(BankAccountServiceImpl.java:41)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:62)
2019-03-28 18:17:16 - 1 - [main] ERROR com.capgemini.bankapp.service.impl.BankAccountServiceImpl  - Exception
com.cagemini.bankapp.exception.BankAccountNotFoundException: Bank Account doesn't exist
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.deposit(BankAccountServiceImpl.java:66)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.fundTransfer(BankAccountServiceImpl.java:88)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:108)
2019-03-28 18:17:16 - 1 - [main] ERROR com.capgemini.bankapp.client.BankAccountClient  - Account Not Found
com.cagemini.bankapp.exception.BankAccountNotFoundException: Bank Account doesn't exist
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.deposit(BankAccountServiceImpl.java:66)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.fundTransfer(BankAccountServiceImpl.java:88)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:108)
2019-03-28 18:17:41 - 24878 - [main] ERROR com.capgemini.bankapp.service.impl.BankAccountServiceImpl  - Exception
com.cagemini.bankapp.exception.BankAccountNotFoundException: Bank Account doesn't exist
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.deposit(BankAccountServiceImpl.java:66)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.fundTransfer(BankAccountServiceImpl.java:88)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:108)
2019-03-28 18:17:41 - 24894 - [main] ERROR com.capgemini.bankapp.client.BankAccountClient  - Account Not Found
com.cagemini.bankapp.exception.BankAccountNotFoundException: Bank Account doesn't exist
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.deposit(BankAccountServiceImpl.java:66)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.fundTransfer(BankAccountServiceImpl.java:88)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:108)
2019-03-28 18:21:42 - 0 - [main] ERROR com.capgemini.bankapp.service.impl.BankAccountServiceImpl  - Exception
com.cagemini.bankapp.exception.BankAccountNotFoundException: Bank Account doesn't exist
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.deposit(BankAccountServiceImpl.java:66)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.fundTransfer(BankAccountServiceImpl.java:88)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:108)
2019-03-28 18:21:42 - 0 - [main] ERROR com.capgemini.bankapp.client.BankAccountClient  - Account Not Found
com.cagemini.bankapp.exception.BankAccountNotFoundException: Bank Account doesn't exist
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.deposit(BankAccountServiceImpl.java:66)
	at com.capgemini.bankapp.service.impl.BankAccountServiceImpl.fundTransfer(BankAccountServiceImpl.java:88)
	at com.capgemini.bankapp.client.BankAccountClient.main(BankAccountClient.java:108)
